# https://www.robinwieruch.de/docker-react-development

FROM node:14.4.0-alpine3.10

WORKDIR /app

COPY package.json ./
COPY webpack.config.js ./
RUN apk add git
RUN npm install

COPY /src ./src
COPY /dist ./dist

EXPOSE 8080

CMD [ "npm", "start" ]
#CMD tail -f /dev/null